# Generated by Django 5.2.2 on 2025-06-14 18:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='business_goals/')),
                ('status', models.CharField(choices=[('PENDING_ANALYSIS', 'Pending Analysis'), ('ANALYZED', 'Analyzed'), ('RECOMMENDATIONS_APPLIED', 'Recommendations Applied'), ('CLOSED', 'Closed')], default='PENDING_ANALYSIS', max_length=30)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('CURRENT', 'Current'), ('PROPOSED', 'Proposed'), ('DEPRECATED', 'Deprecated'), ('ARCHIVED', 'Archived')], default='CURRENT', max_length=20)),
                ('strategic_importance', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.capability')),
            ],
            options={
                'verbose_name_plural': 'Capabilities',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CapabilityRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('ADD_CAPABILITY', 'Add New Capability'), ('MODIFY_CAPABILITY', 'Modify Existing Capability'), ('STRENGTHEN_CAPABILITY', 'Strengthen Existing Capability'), ('REMOVE_CAPABILITY', 'Remove Capability')], max_length=30)),
                ('proposed_name', models.CharField(blank=True, max_length=200, null=True)),
                ('proposed_description', models.TextField(blank=True, null=True)),
                ('additional_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('recommended_by_ai_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('business_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.businessgoal')),
                ('proposed_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposed_children', to='core.capability')),
                ('target_capability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.capability')),
            ],
            options={
                'ordering': ['-recommended_by_ai_at'],
            },
        ),
        migrations.CreateModel(
            name='VectorEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('CAPABILITY', 'CAPABILITY'), ('BUSINESS_GOAL', 'BUSINESS_GOAL'), ('RECOMMENDATION', 'RECOMMENDATION')], max_length=50)),
                ('object_id', models.CharField(max_length=100)),
                ('vector_index', models.IntegerField()),
                ('text_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_vector_content_d1f398_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
