# Generated by Django 5.2.1 on 2025-05-31 20:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='business_goals/pdfs/')),
                ('status', models.CharField(choices=[('PENDING_ANALYSIS', 'Pending Analysis'), ('ANALYZED', 'Analyzed'), ('RECOMMENDATIONS_APPLIED', 'Recommendations Applied'), ('CLOSED', 'Closed')], max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('level', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('CURRENT', 'Current'), ('PROPOSED', 'Proposed'), ('DEPRECATED', 'Deprecated'), ('ARCHIVED', 'Archived')], max_length=20)),
                ('strategic_importance', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.capability')),
            ],
        ),
        migrations.CreateModel(
            name='CapabilityRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('ADD_CAPABILITY', 'Add Capability'), ('MODIFY_CAPABILITY', 'Modify Capability'), ('DELETE_CAPABILITY', 'Delete Capability'), ('STRENGTHEN_CAPABILITY', 'Strengthen Capability'), ('MERGE_CAPABILITIES', 'Merge Capabilities'), ('SPLIT_CAPABILITY', 'Split Capability')], max_length=30)),
                ('proposed_name', models.CharField(blank=True, max_length=255, null=True)),
                ('proposed_description', models.TextField(blank=True, null=True)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected')], max_length=20)),
                ('recommended_by_ai_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('business_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.businessgoal')),
                ('proposed_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_parent_recommendations', to='core.capability')),
                ('target_capability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='core.capability')),
            ],
        ),
    ]
