# Generated by Django 5.2.2 on 2025-06-05 14:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_enhanced_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('CAPABILITY', 'Capability'), ('BUSINESS_GOAL', 'Business Goal'), ('RECOMMENDATION', 'Recommendation')], help_text='Type of content this embedding represents', max_length=20)),
                ('object_id', models.UUIDField(help_text='UUID of the related object (Capability, BusinessGoal, or CapabilityRecommendation)')),
                ('embedding_model', models.CharField(default='text-embedding-004', help_text='Model used to generate the embedding', max_length=100)),
                ('vector_index', models.IntegerField(help_text='Index position in the FAISS vector store')),
                ('text_content', models.TextField(help_text='The original text content that was embedded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vector Embedding',
                'verbose_name_plural': 'Vector Embeddings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_vector_content_d1f398_idx'), models.Index(fields=['content_type', 'vector_index'], name='core_vector_content_3a93bc_idx'), models.Index(fields=['embedding_model'], name='core_vector_embeddi_534242_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_embedding_per_object'), models.UniqueConstraint(fields=('content_type', 'vector_index'), name='unique_vector_index_per_content_type')],
            },
        ),
    ]
