# Generated by Django 5.2.2 on 2025-06-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vectorembedding'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='capabilityrecommendation',
            name='applied_recommendations_have_timestamp',
        ),
        migrations.AddConstraint(
            model_name='capabilityrecommendation',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'PENDING'), ('status', 'REJECTED'), ('applied_at__isnull', False), _connector='OR'), name='applied_recommendations_have_timestamp'),
        ),
    ]
