# Generated by Django 5.2.2 on 2025-06-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_simplify_models'),
    ]

    operations = [
    ]
