# Generated by Django 5.2.2 on 2025-06-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reset_migration_state'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to only update Django's migration state
        # without executing database operations (since constraints were already removed in 0006)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # No database operations needed - constraints already removed
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='capability',
                    name='valid_capability_level',
                ),
                migrations.RemoveConstraint(
                    model_name='capability',
                    name='unique_capability_name_per_parent',
                ),
                migrations.RemoveConstraint(
                    model_name='capabilityrecommendation',
                    name='applied_recommendations_have_timestamp',
                ),
                migrations.RemoveConstraint(
                    model_name='vectorembedding',
                    name='unique_embedding_per_object',
                ),
                migrations.RemoveConstraint(
                    model_name='vectorembedding',
                    name='unique_vector_index_per_content_type',
                ),
                migrations.RemoveIndex(
                    model_name='businessgoal',
                    name='core_busine_status_08f5c3_idx',
                ),
                migrations.RemoveIndex(
                    model_name='businessgoal',
                    name='core_busine_title_ae698f_idx',
                ),
                migrations.RemoveIndex(
                    model_name='capability',
                    name='core_capabi_status_d9026d_idx',
                ),
                migrations.RemoveIndex(
                    model_name='capability',
                    name='core_capabi_parent__277f92_idx',
                ),
                migrations.RemoveIndex(
                    model_name='capability',
                    name='core_capabi_name_c90319_idx',
                ),
                migrations.RemoveIndex(
                    model_name='capabilityrecommendation',
                    name='core_capabi_busines_8e6788_idx',
                ),
                migrations.RemoveIndex(
                    model_name='capabilityrecommendation',
                    name='core_capabi_recomme_c3d7fd_idx',
                ),
                migrations.RemoveIndex(
                    model_name='capabilityrecommendation',
                    name='core_capabi_target__6dc184_idx',
                ),
                migrations.RemoveIndex(
                    model_name='vectorembedding',
                    name='core_vector_content_d1f398_idx',
                ),
                migrations.RemoveIndex(
                    model_name='vectorembedding',
                    name='core_vector_content_3a93bc_idx',
                ),
                migrations.RemoveIndex(
                    model_name='vectorembedding',
                    name='core_vector_embeddi_534242_idx',
                ),
            ]
        ),
    ]
