# Generated by Django 5.2.2 on 2025-06-14 17:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fix_constraint_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessgoal',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='capability',
            options={'ordering': ['level', 'name'], 'verbose_name_plural': 'Capabilities'},
        ),
        migrations.AlterModelOptions(
            name='capabilityrecommendation',
            options={'ordering': ['-recommended_by_ai_at']},
        ),
        migrations.AlterModelOptions(
            name='vectorembedding',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='vectorembedding',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AddField(
            model_name='businessgoal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='businessgoal',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='business_goals/'),
        ),
        migrations.AlterField(
            model_name='businessgoal',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='businessgoal',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='capability',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='capability',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='capability',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='owner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='capability',
            name='strategic_importance',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='capabilityrecommendation',
            name='additional_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='capabilityrecommendation',
            name='proposed_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capabilityrecommendation',
            name='proposed_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='capabilityrecommendation',
            name='proposed_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposed_children', to='core.capability'),
        ),
        migrations.AlterField(
            model_name='capabilityrecommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('ADD_CAPABILITY', 'Add New Capability'), ('MODIFY_CAPABILITY', 'Modify Existing Capability'), ('STRENGTHEN_CAPABILITY', 'Strengthen Existing Capability'), ('REMOVE_CAPABILITY', 'Remove Capability')], max_length=30),
        ),
        migrations.AlterField(
            model_name='capabilityrecommendation',
            name='recommended_by_ai_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capabilityrecommendation',
            name='target_capability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.capability'),
        ),
        migrations.AlterField(
            model_name='vectorembedding',
            name='content_type',
            field=models.CharField(choices=[('CAPABILITY', 'CAPABILITY'), ('BUSINESS_GOAL', 'BUSINESS_GOAL'), ('RECOMMENDATION', 'RECOMMENDATION')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vectorembedding',
            name='object_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='vectorembedding',
            index=models.Index(fields=['content_type', 'object_id'], name='core_vector_content_d1f398_idx'),
        ),
        migrations.RemoveField(
            model_name='vectorembedding',
            name='embedding_model',
        ),
    ]
